### ISSUE TITLE
Request to create theme for other terminal

### ISSUE THREAD

**Issue by ciscohack** [Drakenlords/Gruvbox-DrakenLords#1]
Hello Expert,

Could you please create this wonderful theme for kitty and iterm2 terminal. I hope you accept my request

**Comment by Drakenlords** [comment]
> Hello Expert,
> 
> Could you please create this wonderful theme for kitty and iterm2 terminal. I hope you accept my request

in this moment the project is stopped (university studios) but i will try to do that proyect!!!

**Comment by ciscohack** [comment]
Sure thanks, i will wait for this great theme
